name: Matrix Demo
on: push
jobs:
  build:
    # Instructs to continue with errors that may exist even if some jobs or combination fails
    continue-on-error: true
    # With matrix you can run a job on different configurations
    # Use "strategy" to apply matrix
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        # Using "include" can help in specifing combinations of keys to run from the matrix
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        # The "exclude" key is used to omit some combinations
        exclude:
          - node-version: 12
            operating-system: ubuntu-latest
    # U can set the runner dynamically using your matrix
    # This would make the build job run multiple times for the different operating system in the matrix
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build