name: Reuseable Deploy
# For a workflow to be reuseable, it must be callable by other workflow
# workflow_call event allows a workflow to be able to be called from other workflows
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result: 
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    # You can specify secrets for the workflow
    # secrets:
    #   some-secret:
    #     required: true
jobs:
  deploy:
    # Make the output of the job the output value of what is returned from the reusable workflow
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          # create a dynamic artifact where the value can be parsed in
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result
        run: echo "step-result=echo 'success'" >> $GITHUB_OUTPUT